spring.application.name=ai-service
server.port=8091

# Google Gemini Configuration
spring.ai.google.genai.api-key=AIzaSyD6frSvlEOq4RdKxbjj4vaV1E2tSUAe4nM
# Try using 1.5-flash first as it has the most stable free-tier allocation
spring.ai.google.genai.chat.options.model=gemini-flash-latest
  spring.ai.google.genai.chat.options.temperature=0.5

# Eureka Configuration
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka