spring.application.name=ai-service
server.port=8091

# GROQ API Key
ai.groq.api-key=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
ai.groq.url=https://api.groq.com/openai/v1/chat/completions
# Eureka Configuration
eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka

ltZone=http://localhost:8761/eureka