spring.application.name=analyze-service

server.port=8085


spring.jpa.hibernate.ddl-auto=update
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.datasource.url=jdbc:mysql://localhost:3306/moodlyze_1.0-analyze-service?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=mysql7678


#jpa vendor adapter configuration
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
spring.jpa.generate-ddl=true
spring.jpa.show-sql=true

eureka.instance.client.serverUrl.defaultZone=http://localhost:8761/eureka

# -------- ZIPKIN + TRACING --------
management.tracing.sampling.probability=1.0
management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
